services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: bills_manager_db
    ports:
      - "5432:5432"
    volumes:
      - bills_manager_db_data:/var/lib/postgresql/data

volumes:
  bills_manager_db_data:
